### ISSUE TITLE
superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead).

### ISSUE THREAD

**Issue by wjordan** [rails/rails-perftest#14]
I see this warning when running this library in Rails 4.2.1:
`DEPRECATION WARNING: superclass_delegating_accessor is deprecated and will be removed from Rails 5.0 (use class_attribute instead).`

(See rails/rails#14271 for discussion)

**Comment by senny** [comment]
@wjordan thank you for reporting. Just pushed a fix and will cut a new release shortly.
