### ISSUE TITLE
Don't know how to build task 'test:prepare'

### ISSUE THREAD

**Issue by benoittgt** [rails/rails-perftest#16]
Hello there

I'm using the `rails-perftest` and `ruby-prof` and trying to run test using [benchmarks project](https://github.com/Borzik/ams-jbuilder-pg/tree/jbuilder) but I have an issue with the rake task:

```shell
bti:ams-jbuilder-pg/ (ams✗) $ rake test:benchmark
rake aborted!
Don't know how to build task 'test:prepare'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `block in load'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:232:in `load_dependency'
/Users/bti/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:241:in `load'
-e:1:in `<main>'
Tasks: TOP => test:benchmark
(See full trace by running task with --trace)
```

No problem with the generator.
```shell
bti:ams-jbuilder-pg/ (ams✗) $ rails generate performance_test homepage
      create  test/performance/homepage_test.rb
```

Any ideas of the problem?

**Comment by benoittgt** [comment]
Found a fix here :  https://github.com/rspec/rspec-rails/issues/936#issuecomment-36129887

Add `task 'test:prepare'` in the Rakefile.

**Comment by kundansingh27feb** [comment]
Getting below error while running rake command:

rake aborted!
Don't know how to build task 'imageOptimize' (See the list of available tasks with `rake --tasks`)
/home/devtest/.rvm/gems/ruby-2.3.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => default
