### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by claudiob** [rails/rails-perftest#27]
Running `rake test:benchmark` on a Rails app generated from the current master rails/rails@5746638 raises an error:

```sh
LoadError: cannot load such file -- rails/test_unit/sub_test_task
.../rails-perftest-4faa9b5314cc/lib/rails/perftest/railties/testing.tasks:1:in `require'
```

The reason is that [this line of code](https://github.com/rails/rails-perftest/blob/4faa9b5314cc266c2444aba3263f87ce22642867/lib/rails/perftest/railties/testing.tasks#L1) requires  `rails/test_unit/sub_test_task` but Rails 5 does not have this file anymore since it was removed in [3297909](https://github.com/rails/rails/commit/3297909cdc4fb114df96b0e74ff5d55c210650cf#diff-6a1093c8397b2b61b6590baf91a9601b).

Thanks again for this great library! :crown:

**Comment by connorshea** [comment]
I think this was fixed in 8f8d84489b79ece2afac3f7ddcda2e08c80b9346?
