### ISSUE TITLE
Compatibility with ruby-prof 0.16

### ISSUE THREAD

**Issue by januszm** [rails/rails-perftest#38]
See https://github.com/ruby-prof/ruby-prof/blob/master/CHANGES , there are major changes to the `print` method in commit: https://github.com/ruby-prof/ruby-prof/commit/24a267bc7b50dc743930945acdaccfdca2417e94

After upgrading ruby-prof to 0.16.x I get this error message:

```
...gems/ruby-prof-0.16.2/lib/ruby-prof/printers/call_tree_printer.rb:46
  in `print': wrong number of arguments (2 for 0..1) (ArgumentError)
...gems/rails-perftest-0.0.6/lib/rails/perftest/active_support/testing/performance/ruby.rb:54
  in `block (2 levels) in record'
```

ruby-prof `print` now takes one `options = {}` argument

**Comment by taq** [comment]
Reverting back to `ruby-prof 0.15.9` solved my problem, but people needs to take a look at this.

**Comment by daveshah** [comment]
Same issue for me and reverting worked as well 👍

**Comment by yangliyi** [comment]
Reverting does the trick. This saved my day 😄

**Comment by seafr** [comment]
As a workaround, you can set `profile_options` explicitly in your test file so the `formats` option does not include `:call_tree` (assuming you don't need it).

`self.profile_options = { runs: 5, formats: [:flat, :graph_html], metrics: ... }` works for me.

I'm using:
* `ruby-prof (0.17.0)`
* `rails-perftest (0.0.7)`

**Comment by mistersourcerer** [comment]
I have opened a PR https://github.com/rails/rails-perftest/pull/48 trying to address this issue, maybe it can be useful.
