### ISSUE TITLE
Do you have any plan to update gem version?

### ISSUE THREAD

**Issue by kazu9su** [rails/rails-perftest#47]
I need [this change](https://github.com/rails/rails-perftest/commit/8f2e43a425460164792222765ea80aec41783bda) to run Rails-perftest test with minitest5.11.3.

So I want to know the plan to update including this if you have.

Thanks!

**Comment by awaltman** [comment]
Could the maintainers please comment on this or release a new version? Is the gem no longer being maintained?

**Comment by rafaelfranca** [comment]
You can always use the master branch if you need something. Bundler is there to help us. There is no plan to release this gem, it may happen, but we are not planning to do it now.
