### ISSUE TITLE
Is this project still mantained?

### ISSUE THREAD

**Issue by rvalenciano** [rails/rails-perftest#51]
Hi,

Would like to do some benchmark testing. Is this still be mantained? Getting some errors and not finding too much support in SO/Github.

**Comment by doutatsu** [comment]
Same question here. But looks like it's dead

**Comment by rafaelfranca** [comment]
There is no official maintainer for this project. It is here to use as is and people will probably merge PRs if any is open to fix issues but we are not actively working to fix issue on this project

**Comment by cyclingzealot** [comment]
@rafaelfranca Is there an alternate project / gem that's preferred for benchmarking or are you looking for a maintainer?

@rvalenciano Did you end up choosing a different project / gem?

**Comment by rvalenciano** [comment]
@cyclingzealot I'm now using [Benchmark IPS](https://github.com/evanphx/benchmark-ips) for benchmarking regarding profiling I decided to follow Nate Berkopec's recommendations in his book about Rails Performance. So basically, using [derailed_benchmarks](https://github.com/zombocom/derailed_benchmarks) and [memory_profiler](https://github.com/SamSaffron/memory_profiler).
